name = "Write-Only Hugo Theme"
license = "MIT"
licenselink = "https://github.com/writeonlycode/writeonlyhugo/blob/master/LICENSE"
description = "A simple, clean and straightforward blog theme."

homepage = "https://github.com/writeonlycode/writeonlyhugo/"
demosite = "https://writeonlycode.github.io/writeonlyhugo/"

tags = ["blog", "responsive", "personal", "light", "bootstrap" ]
features = []

[author]
  name = "Iago Bozza"
  homepage = "https://iagobozza.com/"
