baseURL: "https://www.example.com/"
theme: "github.com/writeonlycode/writeonlyhugo"
languageCode: "en-us"

title: "Write-Only Hugo"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Write-Only Hugo"
  description: "A simple, clean and straightforward blog theme."

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"

taxonomies:
  categories: "categories"
  series: "series"
  tags: "tags"

modules:
  imports:
    - path: "gitlab.com/writeonlyhugo/writeonlyhugo-theme"

